"""modif unique key of username

Revision ID: 03d2a703c239
Revises: ddfadc83c01e
Create Date: 2016-05-17 19:15:43.263761

"""

# revision identifiers, used by Alembic.
revision = '03d2a703c239'
down_revision = 'ddfadc83c01e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_username', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    ### end Alembic commands ###
