"""ajout model firm

Revision ID: 1072b41deb37
Revises: 0f67812c589e
Create Date: 2016-05-19 18:08:26.783509

"""

# revision identifiers, used by Alembic.
revision = '1072b41deb37'
down_revision = '0f67812c589e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firm_name'), 'firm', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firm_name'), table_name='firm')
    op.drop_table('firm')
    ### end Alembic commands ###
