"""add project model

Revision ID: 32945954c196
Revises: fe88c90a744a
Create Date: 2016-05-25 17:16:20.732857

"""

# revision identifiers, used by Alembic.
revision = '32945954c196'
down_revision = 'fe88c90a744a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_intra', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('desc', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id_intra'), 'project', ['id_intra'], unique=True)
    op.create_index(op.f('ix_project_name'), 'project', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_name'), table_name='project')
    op.drop_index(op.f('ix_project_id_intra'), table_name='project')
    op.drop_table('project')
    ### end Alembic commands ###
