"""empty message

Revision ID: 40f2aeeff47a
Revises: 9b386309d33f
Create Date: 2016-06-02 16:02:45.167572

"""

# revision identifiers, used by Alembic.
revision = '40f2aeeff47a'
down_revision = '9b386309d33f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrat', sa.Column('projects', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contrat', 'projects')
    ### end Alembic commands ###
