"""empty message

Revision ID: 51fd291c0216
Revises: 32945954c196
Create Date: 2016-05-30 11:46:17.012433

"""

# revision identifiers, used by Alembic.
revision = '51fd291c0216'
down_revision = '32945954c196'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_project_id_intra', table_name='project')
    op.create_index(op.f('ix_project_id_intra'), 'project', ['id_intra'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_id_intra'), table_name='project')
    op.create_index('ix_project_id_intra', 'project', ['id_intra'], unique=True)
    ### end Alembic commands ###
