"""empty message

Revision ID: 6c062d91abdc
Revises: ace2fdb04770
Create Date: 2016-06-02 16:45:25.947155

"""

# revision identifiers, used by Alembic.
revision = '6c062d91abdc'
down_revision = 'ace2fdb04770'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('mobile', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_mobile'), 'user', ['mobile'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_mobile'), table_name='user')
    op.drop_column('user', 'mobile')
    ### end Alembic commands ###
