"""add email to user model

Revision ID: 97d0f352f19b
Revises: ccb166caae04
Create Date: 2016-05-17 22:42:30.591388

"""

# revision identifiers, used by Alembic.
revision = '97d0f352f19b'
down_revision = 'ccb166caae04'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_column('user', 'email')
    ### end Alembic commands ###
