"""empty message

Revision ID: a72cd3955497
Revises: 51fd291c0216
Create Date: 2016-05-31 15:26:09.135437

"""

# revision identifiers, used by Alembic.
revision = 'a72cd3955497'
down_revision = '51fd291c0216'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('firm_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['firm_id'], ['firm.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contrat_name'), 'contrat', ['name'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contrat_name'), table_name='contrat')
    op.drop_table('contrat')
    ### end Alembic commands ###
