"""empty message

Revision ID: ace2fdb04770
Revises: 40f2aeeff47a
Create Date: 2016-06-02 16:34:01.080476

"""

# revision identifiers, used by Alembic.
revision = 'ace2fdb04770'
down_revision = '40f2aeeff47a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrat', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'contrat', 'project', ['project_id'], ['id'])
    op.drop_column('contrat', 'projects')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contrat', sa.Column('projects', mysql.VARCHAR(length=128), nullable=True))
    op.drop_constraint(None, 'contrat', type_='foreignkey')
    op.drop_column('contrat', 'project_id')
    ### end Alembic commands ###
