"""add role relationship

Revision ID: df244c6cf4f3
Revises: 322a3374b317
Create Date: 2016-05-19 22:59:35.118284

"""

# revision identifiers, used by Alembic.
revision = 'df244c6cf4f3'
down_revision = '322a3374b317'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'role_id')
    ### end Alembic commands ###
