"""add firm_id

Revision ID: fe88c90a744a
Revises: df244c6cf4f3
Create Date: 2016-05-20 10:52:21.940305

"""

# revision identifiers, used by Alembic.
revision = 'fe88c90a744a'
down_revision = 'df244c6cf4f3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firm_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'firm', ['firm_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'firm_id')
    ### end Alembic commands ###
